name: Create update manifest
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r DevOps/requirements.txt

      - name: Create and commit manifest
        shell: bash
        run: |
          export GIT_REV_COUNT="$(git rev-list --count HEAD)"
          export GIT_HISTORY="$(git log --pretty=format:"%H")"

          export MANIFEST_LOCATION="$(mktemp --suffix ".json")"

          python DevOps/create_update_manifest.py "${MANIFEST_LOCATION}"

          # Aggressive switch to info/auto-updater
          git switch info/auto-updater
          git reset --hard info/auto-updater
          git clean -dfx

          # GitHub Actions user setup
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          # Move manifest here
          mv "${MANIFEST_LOCATION}" ./manifest.json

          # Commit it
          git add .
          git commit -m "Update manifest to latest release version"
          git push
